name: Deploy Spring Boot App

on:
  push:
    branches: [ "master" ]  # or [dev, Test] if you want both branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd ~/rent-car-system/RentaCar-Management-System || mkdir ~/rent-car-system/RentaCar-Management-System && cd ~/rent-car-system/RentaCar-Management-System
            rm -rf ./*
          EOF

          rsync -avz --exclude 'target/' ./ ${{ secrets.USER }}@${{ secrets.HOST }}:~/rent-car-system/RentaCar-Management-System/

          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd ~/rent-car-system/RentaCar-Management-System
            docker build --no-cache -t rent-system-image .
            docker stop rent-system-container || true
            docker rm rent-system-container || true
            docker run -d --name rent-system-container --restart=always -p 8080:8080 rent-system-image
            sudo systemctl restart rent-system
          EOF
